### PR TITLE
add SupportType AAAA fix, add padding param, make edns argv optional for Best guess, Update index.js

### PR DESCRIPTION
**Pull request by Opensourcecommunitydevelopment**
Check AAAA got fixed :-) i have tried To comment some change decisssions.

### CODE REVIEW

**Comment by yyfrankyy** [comment]
Thanks a lot.

I've added a commit for code-style fix. could u might add the dependencies to `package.json` and do a amend commit to this PR? I'd like to keep the git-log as clean as possible.

```
npm i ip6 randomstring --save
```

**Comment by Opensourcecommunitydevelopment** [comment]
thanks for simplify query and teaching auto dependency adding command :) appended package.json here now.

I did not append edns_client_subnet param with:`
if( typeof subnet !== 'undefined' && subnet )query[0]='';`        results in resolve?&name=github.com
removing it completely from query. if no subnet set. 
because passing an empty value is should not be needed? (resolve?edns_client_subnet=&name=... )

but if argv isset may it should contain the "subnet" too for correct format the doc says this as far i understand this?

edns_client_subnet
string, default: empty

The edns0-client-subnet option. Format is an IP address with a subnet mask. Examples: 1.2.3.4/24, 2001:700:300::/48.

if have not compared the results yet of edns_client_subnet formatting

**Review by yyfrankyy — APPROVED** [review]

**Comment by Opensourcecommunitydevelopment** [comment]
hello, you removed My ends line and Put instead
 subnet||'' 

but if you provide this query param, it can't be empty or give error Response. It can be completely empty (Default) but Not appear in request even as emtpy in this case! 

now if i Run without subnet argv i get error from google: `'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=
1, width=device-width">\n  <title>Error 400 (Bad Request)!!1</title>\n  <style>\n    _{margin:0;padding:0}html,code{font
:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-heigh
t:180px;padding:30px 0 15px}_ > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding
-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (
max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com
/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-res
olution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-re
peat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png)
 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/goog
lelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:
54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>400.</b>
 <ins>That’s an error.</ins>\n  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins

> \n'`

please chkeck Let query[0] to be never edns_client_subnet:'',

**Comment by yyfrankyy** [comment]
Fixed.

I wasn't understanding the `query[0]` before, looks like that Google need this to be empty while querying AAAA, that's odd.

**Pull request merged**
